name: ci pipeline

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      TELEX_RETURN_URL: ${{ secrets.TELEX_RETURN_URL }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: python manage.py test